import "../globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Toaster } from "@/components/ui/toaster";
import SidebarProvider from "@/providers/sidebar-provider";
import { ThemeProvider } from "@/providers/theme-provider";
import { FeelingsSidebar } from "@/components/sidebar/feelings-sidebar";
import { SidebarContainer } from "@/components/sidebar/sidebar-container";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Duygu Düzenleme ve Takibi ",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
