import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SidebarProvider from "@/providers/sidebar-provider";
import { ThemeProvider } from "@/providers/theme-provider";
import { Sidebar } from "@/components/sidebar";
import { FeelingsSidebar } from "@/components/feelings-sidebar";
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SidebarProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            <main>
              <div className="min-h-screen flex ">
                <Sidebar />
                <FeelingsSidebar />
                <div className="w-full flex flex-1 flex-col items-center justify-center">
                  {children} <Toaster />
                </div>
              </div>
            </main>
          </ThemeProvider>
        </SidebarProvider>
      </body>
    </html>
  );
}
