import "../globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Toaster } from "@/components/ui/toaster";
import SidebarProvider from "@/providers/sidebar-provider";
import { ThemeProvider } from "@/providers/theme-provider";
import { FeelingsSidebar } from "@/components/sidebar/feelings-sidebar";
import { SidebarContainer } from "@/components/sidebar/sidebar-container";
import { getUserFullName } from "../auth/dal";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Duygu Düzenleme ve Takibi ",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getUserFullName();

  return (
    <html lang="en">
      <body className={inter.className}>
        <SidebarProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            <main>
              <div className="flex h-screen overflow-hidden">
                <SidebarContainer user={user} />
                <FeelingsSidebar />

                <div className="w-full flex flex-1 flex-col items-center justify-center">
                  {children} <Toaster />
                </div>
              </div>
            </main>
          </ThemeProvider>
        </SidebarProvider>
      </body>
    </html>
  );
}
